# Generated by Django 4.1 on 2024-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShipList",
            fields=[
                (
                    "code",
                    models.IntegerField(
                        db_column="CODE", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="NAME", max_length=200)),
                (
                    "type",
                    models.CharField(
                        blank=True, db_column="TYPE", max_length=30, null=True
                    ),
                ),
                (
                    "length",
                    models.IntegerField(blank=True, db_column="LENGTH", null=True),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, db_column="HEIGHT", null=True),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, db_column="WIDTH", null=True),
                ),
                (
                    "waterline",
                    models.IntegerField(blank=True, db_column="WATERLINE", null=True),
                ),
            ],
            options={
                "db_table": "ship_list",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_column="ID",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pw",
                    models.CharField(
                        blank=True, db_column="PW", max_length=15, null=True
                    ),
                ),
                (
                    "dept",
                    models.CharField(
                        blank=True, db_column="DEPT", max_length=20, null=True
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="TEL", max_length=20, null=True
                    ),
                ),
                (
                    "e_mail",
                    models.CharField(
                        blank=True, db_column="E_MAIL", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "user_list",
                "managed": False,
            },
        ),
    ]
